all:
  hosts:
    workforce-prod:
      ansible_host: 173.249.30.3
      ansible_user: root          # bootstrap phase; becomes workforce_app_sa after
      service_user: workforce_app_sa
      base_domain: careangelssupport.com
      app_hostname: workforce.careangelssupport.com
      auth_hostname: auth.careangelssupport.com
      env_name: prod
      tls_mode: production
